[package]
name = "yattecast-post-generate"
version = "0.1.0"
authors = ["Yuya Hirayama <yuya-hirayama@cookpad.jp>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_yaml = "0.8"
serde_derive = "1.0"
chrono = "0.4.6"
